version: '3.8'

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './express:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 8081:8080
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --max_allowed_packet=8532505856 --wait_timeout=58800
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    # TODO: Enable networks
    #networks:
    #  - dbNetwork
    ports:
      - 8086:3306
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db

#networks:
#    dbNetwork:

volumes: 
  dbdata:

# Sources: https://hub.docker.com/_/mysql, https://hub.docker.com/r/phpmyadmin/phpmyadmin/, https://www.bezkoder.com/docker-compose-react-nodejs-mysql/, https://mherman.org/blog/dockerizing-a-react-app/, https://tecadmin.net/docker-compose-persistent-mysql-data/