version: '3.8'

services:

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - server
    networks:
      - dbNetwork
    depends_on:
      - server

  server:
    container_name: server
    restart: unless-stopped
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - "./server:/server"
    ports:
      - "3001:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
    networks:
      - dbNetwork
    links:
      - db

  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --max_allowed_packet=8532505856 --wait_timeout=58800
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - dbNetwork

#  phpmyadmin:
#    image: phpmyadmin:5
#    restart: always
#    ports:
#      - 8080:80
#    environment:
#      - PMA_HOST=${DB_HOST}
#    depends_on:
#      - db
#    links:
#      - db
#    networks:
#      - dbNetwork

networks:
    dbNetwork:

volumes: 
  dbdata:

# Sources: https://hub.docker.com/_/mysql, https://hub.docker.com/r/phpmyadmin/phpmyadmin/, https://www.bezkoder.com/docker-compose-react-nodejs-mysql/, https://mherman.org/blog/dockerizing-a-react-app/, https://tecadmin.net/docker-compose-persistent-mysql-data/