version: '3.8'

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './express:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 8081:8080
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    # TODO: Enable networks
    #networks:
    #  - dbNetwork
    ports:
      - 8086:3306
    volumes:
<<<<<<< HEAD
      - ./data/db:/var/lib/mysql
  #  networks:
  #    - backend
=======
      - dbdata:/var/lib/mysql
>>>>>>> 975c82d7c92675934c4f478940f72708e1867a35

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db

<<<<<<< HEAD
#volumes: 
#  dbdata:
=======
#networks:
#    dbNetwork:

volumes: 
  dbdata:
>>>>>>> 975c82d7c92675934c4f478940f72708e1867a35

# Sources: https://hub.docker.com/_/mysql, https://hub.docker.com/r/phpmyadmin/phpmyadmin/, https://www.bezkoder.com/docker-compose-react-nodejs-mysql/, https://mherman.org/blog/dockerizing-a-react-app/, https://tecadmin.net/docker-compose-persistent-mysql-data/